/*
 * @Author: wdy
 * @Date: 2021-01-07 16:42:26
 * @Last Modified by: wdy
 * @Last Modified time: 2021-01-07 16:42:53
 */
const MENU = 'MENU'; // 菜单
const INTERNAL_PAGE = 'INTERNAL_PAGE'; // 内置页面
const ASEIT_INSPECTION_PAGE = 'ASEIT_INSPECTION_PAGE'; // 巡检页面
const ASEIT_SETTING_PAGE = 'ASEIT_SETTING_PAGE'; // 配置页面
const FRIEND_INNER_IFREAM = 'FRIEND_INNER_IFREAM'; // 三方内置iframe
const FRIEND_INNER_PAGE = 'FRIEND_INNER_PAGE'; // 三方内部页面
const FRIEND_BLANK_PAGE = 'FRIEND_BLANK_PAGE'; // 三方外置页面

export { MENU, INTERNAL_PAGE, ASEIT_INSPECTION_PAGE, ASEIT_SETTING_PAGE, FRIEND_INNER_IFREAM, FRIEND_INNER_PAGE, FRIEND_BLANK_PAGE };
